@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor user
actor web_ui
control document_service
control aws_S3
queue aws_SNS
control aws_DynamoDB

alt create document
    user -> web_ui: presses the button to create document\nand provides all the necessary information.\nThe Document might be of any kind.
    web_ui -> document_service: HTTP/POST:\n/v1/document-service/write/{entity_name}
    document_service --> document_service: validate request
    document_service --> document_service: generate document
    document_service -> aws_S3: send document to the storage
    return ack & construct metadata
    document_service -> aws_DynamoDb: save document metadata
    return ack
    document_service -> aws_SNS: create topic if non exists
    return topic ARN
    document_service -> aws_SNS: send document metadata into the AWS SNS
    return ack
    document_service --> document_service: remap the metadata response\ninto the REST response
    document_service --> web_ui: return serialised JSON response
    web_ui --> user: represent an acknowledgement
end
alt download document
    user -> web_ui: open the page of all documents\nand sort for a specific type
    web_ui -> document_service: HTTP/POST:\n/v1/document-service/read?documentType={docType}
    document_service -> aws_DynamoDb: find all documents of specific type
    return documents
    document_service --> document_service: map data from the database\nstructure into the REST response
    document_service --> web_ui: return serialised JSON response
    web_ui --> user: represent available documents
    group download file
        user -> web_ui: presses the button to download document
        web_ui -> document_service: HTTP/GET:\n/v1/document-service/read/documents/{documentId}\nContent-Type: application/pdf
        document_service -> aws_S3: download document
        return PDF document
        document_service -> web_ui: PDF file
        web_ui --> user: download document
    end
end

@enduml
