package io.github.sergejsvisockis.documentservice.service;

import io.github.sergejsvisockis.documentservice.service.dto.SentDocumentMetadata;
import io.github.sergejsvisockis.documentservice.sns.DocumentSNSPublisher;
import io.github.sergejsvisockis.documentservice.utils.JsonUtil;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.UUID;

/**
 * This class is a base documentAsBytes processing implementation.
 * Each method is to be implemented by each entity since that is possible
 * that some of them might be saved into the AWS S3, some into the SFT and some others into one another storage.
 * This is why an implementation myst be as generic as possible.
 *
 * @param <T> the request body coming out of the REST service.
 */
public abstract class BaseDocumentWriteService<T, G> {

    @Autowired
    private DocumentSNSPublisher snsPublisher;

    public SentDocumentMetadata process(T request) {
        T validatedRequest = validate(request);

        G document = generate(validatedRequest);

        SentDocumentMetadata sentDocumentMetadata = sendToStorage(document);

        String topicArn = snsPublisher.createTopicIfNotExist("document-saved");
        snsPublisher.publish(topicArn, JsonUtil.toJson(sentDocumentMetadata));

        return save(sentDocumentMetadata);
    }

    /**
     * Validates documentAsBytes request body, which comes from the REST service.
     *
     * @param request the request body
     * @return validated request body
     */
    public abstract T validate(T request);

    /**
     * Supposed to generate PDF documentAsBytes which is supposed to be saved into some sort of storage later on.
     *
     * @param request the request containing the documentAsBytes metadata to insert into the predefined template.
     *                Generator could be any 3rd party subsystem.
     * @return Since PDF is being generated by the 3rd party system via the REST interface is supposed
     * to abstract the file itself.
     */
    public abstract G generate(T request);

    /**
     * Sent the PDF documentAsBytes into the storage.
     * Any storage could be an AWS S3, SFTP, etc.
     *
     * @param request the message request to send to the storage.
     * @return {@link SentDocumentMetadata} saved documentAsBytes metadata
     */
    public abstract SentDocumentMetadata sendToStorage(G request);

    /**
     * Supposed to write saved documentAsBytes metadata.
     *
     * @param request saved documentAsBytes request metadata.
     * @return {@link SentDocumentMetadata} saved documentAsBytes metadata.
     */
    public abstract SentDocumentMetadata save(SentDocumentMetadata request);


    SentDocumentMetadata constructSentDocumentResponse(String fileName, String documentType, String entityType) {
        return new SentDocumentMetadata(
                UUID.fromString(fileName.replace(documentType, "")),
                entityType,
                fileName
        );
    }
}
