openapi: 3.0.3
info:
  title: Document Write Service API
  version: 1.0.0
  description: This is a document write service API specification.
tags:
  - name: document-write-service

servers:
  - url: /document-service/v1

paths:
  /policy-document-write:
    post:
      tags:
        - document-write-service
      summary: Create policy document
      description: Write the policy metadata into the database and trigger PDF generation
      operationId: writePolicyDocument
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PolicyDocumentRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
  /claim-document-write:
    post:
      tags:
        - document-write-service
      summary: Create claim document
      description: Write claim metadata into the database and trigger PDF generation
      operationId: writeClaimDocument
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimDocumentRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
  /invoice-document-write:
    post:
      tags:
        - document-write-service
      summary: Create invoice document
      description: Write an invoice document metadata into the database and trigger PDF generation
      operationId: writeInvoiceDocument
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceDocumentRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'

components:
  schemas:
    PolicyDocumentRequest:
      type: object
      properties:
        insured:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
        owner:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
        policyNumber:
          type: string
        phoneNumber:
          type: string
        address:
          type: string
        city:
          type: string
        relationshipToInsured:
          type: string
        premium:
          type: number
        lob:
          type: string
    ClaimDocumentRequest:
      type: object
      properties:
        claimNumber:
          type: string
        policyNumber:
          type: string
        city:
          type: string
        address:
          type: string
        placeOfIncident:
          type: string
        shortDescription:
          type: string
    InvoiceDocumentRequest:
      type: object
      properties:
        policyNumber:
          type: string
        insured:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
        owner:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
        phoneNumber:
          type: string
        totalPrice:
          type: number
    DocumentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        documentType:
          type: string
        fileName:
          type: string
