openapi: 3.0.3
info:
  title: Document Write Service API
  version: 1.0.0
  description: This is a document write service API specification.
tags:
  - name: document-write-service

servers:
  - url: /document-service/v1

paths:
  /documents/{documentId}:
    get:
      tags:
        - document-read-service
      summary: Get a metadata of the document by its ID
      description: Shall return a metadata of a single document by its ID. Afterwards it is possible to search for that one in the S3.
      operationId: readSingleDocument
      parameters:
        - in: path
          name: documentId
          schema:
            type: string
            format: uuid
          required: true
          description: Searchable document Id
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'

  /documents:
    get:
      tags:
        - document-read-service
      summary: Get a metadata of all the documents by specific type
      description: Shall return a metadata of all the possible documents by its type.
      operationId: readAllDocuments
      parameters:
        - in: query
          name: documentType
          schema:
            type: string
          required: true
          description: Searchable document types
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'

components:
  schemas:
    DocumentResponse:
      type: object
      properties:
        documents:
          type: array
          items:
            $ref: '#/components/schemas/DocumentMetadata'

    DocumentMetadata:
      type: object
      properties:
        id:
          type: string
          format: uuid
        documentType:
          type: string
        fileName:
          type: string
