server:
  port: 8080

spring:
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      dynamodb:
        region: eu-north-1
        endpoint: https://dynamodb.eu-north-1.amazonaws.com
      s3:
        region: eu-north-1
        endpoint: https://s3.eu-north-1.amazonaws.com
        bucket: insurtechstorage
      sns:
        enabled: true
        region: eu-north-1
        endpoint: https://sns.eu-north-1.amazonaws.com
        topic-arn: arn:aws:sns:eu-north-1:117863533677:document-saved
