server:
  port: 8080

spring:
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      dynamodb:
        region: ${REGION}
        endpoint: ${DYNAMODB_ENDPOINT}
      s3:
        region: ${REGION}
        endpoint: ${S3_ENDPOINT}
      sns:
        enabled: true
        region: ${REGION}
        endpoint: ${SNS_ENDPOINT}
